name: EC2 Deployment CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy securely to AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/bloodmate
          
          echo "🔄 Pulling latest secure codebase..."
          git fetch origin main
          git reset --hard origin/main
          
          echo "📦 Rebuilding frontend architecture..."
          cd frontend
          npm install
          npm run build
          
          echo "🐍 Restoring backend dependencies..."
          cd ../backend
          source venv/bin/activate
          pip install -r requirements.txt
          
          echo "🚀 Restarting secure API Services..."
          sudo systemctl restart BloodMate-py
          
          echo "✅ Pipeline successfully executed."
